services:
  # --- BACKEND ---
  backend:
    build: backend
    restart: always
    environment:
      - MYSQL_HOST=db
      - MYSQL_PASSWORD=db-57xsl
    networks:
      - react-spring
      - spring-mysql
    depends_on:
      db:
        condition: service_healthy

  # --- BASE DE DATOS ---
  db:
    image: mariadb:10.6.4-focal
    restart: always
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD=db-57xsl
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - spring-mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-pdb-57xsl", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s

  # --- FRONTEND ---
  frontend:
    build:
      context: frontend
    networks:
      - react-spring

  # --- PROXY (NGINX) ---
  proxy:
    image: nginx:latest
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - react-spring

# --- VOLÃšMENES Y REDES ---
volumes:
  db-data: {}

networks:
  react-spring: {}
  spring-mysql: {}